FROM python:3.12-alpine
RUN apk add --no-cache docker-cli git && \
    git config --system --add safe.directory /srv/jekyll
COPY webhook-deploy.py /webhook-deploy.py
CMD ["python3", "/webhook-deploy.py"]
